
# Воспроизведение "King James Programming" для русского языка, или "Ветхий алгоритм"

http://kingjamesprogramming.tumblr.com/

## Мотивация

Для английского языка есть марковская цепь, натренированная на книгах King James Bible, Structure and Interpretation of Computer Programs, и некоторых записках Эрика Раймонда.

Модель генерирует такие замечательные высказывания, как:
> hath it not been for the singular taste of old Unix, “new Unix” would not exist

Или, моё любимое,
> The interpreter will run slowly this time because of the will of the LORD.

Я подумала и решила: а почему бы не сделать такое для русского?

In [48]:
import re
regex = re.compile("[А-Яа-яA-Za-z!?.]+")

def words_only(text, regex=regex):
    return " ".join(regex.findall(str(text)))

## Данные

В качестве обучающих текстов я взяла Ватхий Завет и книги "Вводный курс алгоритмов" (Кормен) и "UNIX. Профессиональное программирование".

In [49]:
# читаем ветхий завет
with open('bible.txt', encoding='cp1251') as f:
    bible = f.read()
    print(bible[400:500])
    print('***')
#     bible = bible[700:] # там было странное
#     bible = bible[:-365]
print(bible[:500])
print(len(bible))

 от воды. [И стало так.]
7 И создал Бог твердь, и отделил воду, которая под твердью, от воды, котора
***

== Бытие ==

=== 1 ===

1 В начале сотворил Бог небо и землю.
2 Земля же была безвидна и пуста, и тьма над бездною, и Дух Божий носился над водою.
3 И сказал Бог: да будет свет. И стал свет.
4 И увидел Бог свет, что он хорош, и отделил Бог свет от тьмы.
5 И назвал Бог свет днем, а тьму ночью. И был вечер, и было утро: день один.
6 И сказал Бог: да будет твердь посреди воды, и да отделяет она воду от воды. [И стало так.]
7 И создал Бог твердь, и отделил воду, которая под твердью, от воды, котора
4164321


In [50]:
bible = words_only(bible)

In [46]:
# чистим ветхий завет
bible = [re.sub('^[0-9]+ ', '', l) for l in bible.split('\n')]
bible = '\n'.join(bible).replace('=', '')
print(bible[:500])


 Бытие 

 1 

В начале сотворил Бог небо и землю.
Земля же была безвидна и пуста, и тьма над бездною, и Дух Божий носился над водою.
И сказал Бог: да будет свет. И стал свет.
И увидел Бог свет, что он хорош, и отделил Бог свет от тьмы.
И назвал Бог свет днем, а тьму ночью. И был вечер, и было утро: день один.
И сказал Бог: да будет твердь посреди воды, и да отделяет она воду от воды. [И стало так.]
И создал Бог твердь, и отделил воду, которая под твердью, от воды, которая над твердью. И стало т


In [52]:
# Читаем коран
with open('koran.txt', encoding="utf-8") as f:
    koran = f.read()
    koran = koran[137:]
print(koran[:500])
print(len(koran))


Сура 1
        Открывающая Книгу
      
      1. (1). Во имя Аллаха милостивого, милосердного! (2). Хвала — Аллаху, Господу миров,
      2. (3). милостивому, милосердному,
      3. (4). царю в день суда!
      4. (5). Тебе мы поклоняемся и просим помочь!
      5. (6). Веди нас по дороге прямой,
      6. (7). по дороге тех, которых Ты облагодетельствовал,
      7. не тех, которые находятся под гневом, и не заблудших.
      
    
      
        Сура 2
        Корова
      
      1. (1). Алм. (2).
812012


In [53]:
koran = words_only(koran)

In [54]:
# Читаем юникс
with open('unix.txt', encoding="utf-8") as f:
    unix = f.read()
#     unix = unix[82500:]
print(unix[:1500])
print(len(unix))

     1. Предисловие

     В  последнее  время  Internet  очень  часто  оказывается в центре
внимания,  и серьезные люди часто болтаются по этому " Информационному
супершоссе". Компьютерные сети становятся такими же обыденными вещами,
как  телевизоры  и  микроволновые  печи.  Inetrnet  получает  необычно
широкое  освещение  в  печати, а ученые обсуждают в Usenet возможность
проведения   исследований   "Internet  культуры."  Различные  компании
работают над новыми методами передачи данных, например ATM, которые во
многих  случаях  позволяют  получить  большую  скорость  передачи, чем
сейчас.

     Конечно,   сети  развивались  достаточно  долгое  время.  Обычной
практикой   было   создание  маленьких  локальных  сетей,  в  основном
распологавшихся в одном здании, и соединенных через обычные телефонные
линии.   Таким   образом,  быстро  разраставшийся  конгломерат  сетей,
позволял  подсоединятся  к  этой  глобальной  системе  даже  маленьким
некоммерческим  организациям и частным пользова

In [55]:
# чистим юникс
unix = words_only(unix)

## Генератор предложений

### Готовая имплементация марковской цепи

https://github.com/jsvine/markovify

In [41]:
import markovify

In [56]:
text = bible + koran + unix[:10 ** 6]
len(text)

5625234

In [57]:
text_m = markovify.Text(text)

In [58]:
for i in range(5):
    print(text_m.make_sentence())

И сказал мне на небе?
Сура Железо . . Разве для людей которые знают!
Многие же постилали одежды свои Иисус сел на улице городской.
И делал он неугодное в очах Господних точно так как десятину сынов Израилевых они не отвечали ему ни слова.
И помогали ему и сказал с миром отпущены были братиями к Апостолам.


### ... безудержное веселье! 
* Мы начнем со строки Х и будем твердо стоять за народ наш и за беззакония наши преданы были мы, цари наши, священники наши и дети мои вокруг меня, когда светильник Его светил над головою моею, и я забросил клюшку и щиток.
* Но ведь тоrда тщательно выверенная процедура PARTIТION не будет живущих, ибо, кого Ты поразил, они *еще* преследуют, и страдания уязвленных Тобою умножают.
* Шаг 2 выполняется ровно n раз, потому что ячмень выколосился, а лен осеменился; а пшеница и полба не побиты, потому что Господь зовет отрока.
* Иосиф узнал братьев своих, сыновей царя, со всеми слугами своего господина, и не может сразу следовать за выводом без вызова функций fseek, fsetpos или rewind.
* Однако когда программа, использовавшая эту возможность, запускала командную оболочку, чтобы воздействовать на все дни жизни твоей; и очистит священник душу, сделавшую по ошибке согрешит против ближнего своего;
* И из сыновей Заффу: Елиоенай, Елияшив, Матфания, Иремоф, Завад и Азиса; и из сыновей своих, чтоб он спас нас от беспокойства по поводу буферизации или оптимальности выбранного размера буфера
* Жене сказал: умножая умножу потомство твое, так что каждый вызов read или write обращается к системному вызову ядра.
* При захождении солнца приказал Иисус, и сняли их с площади Беф-Сана, где они были перенаправлены в файлы

In [59]:
import pickle

In [60]:
# сохраним его
with open('lm.bin', 'wb') as f:
    pickle.dump(text_m, f)

In [62]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\photo\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.


True

### Напишем свой генератор

In [63]:
from nltk.tokenize import word_tokenize
corpus = word_tokenize(text)
corpus[:20]

['Бытие',
 'В',
 'начале',
 'сотворил',
 'Бог',
 'небо',
 'и',
 'землю',
 '.',
 'Земля',
 'же',
 'была',
 'безвидна',
 'и',
 'пуста',
 'и',
 'тьма',
 'над',
 'бездною',
 'и']

In [64]:
freq = nltk.FreqDist(corpus)
print(freq['Бог'], freq['вызов'])

1914 34


In [65]:
cfreq = nltk.ConditionalFreqDist(nltk.bigrams(corpus))

In [66]:
for key in cfreq['функция']:
    if key[0] in 'йцукенгшщзхфывапролджэячсмитьбю' and cfreq['функция'][key] > 2:
        print(key, cfreq['функция'][key])

In [67]:
capitalized = [w for w in corpus if w[0].isupper()]
capitalized[:10]

['Бытие', 'В', 'Бог', 'Земля', 'Дух', 'Божий', 'И', 'Бог', 'И', 'И']

In [68]:
cprob = nltk.ConditionalProbDist(cfreq, nltk.MLEProbDist)

In [69]:
# функция, которая генерирует предложение из n слов на основании предыдущего слова
import random
def gen_n_words(n, first_word=None):
    if first_word is None:
        first_word = random.choice(capitalized)
    sent = [first_word]
    for i in range(n - 1):
        next_w = cprob[sent[-1]].generate()
        sent.append(next_w)
    return ' '.join(sent)

In [214]:
lengths = [5, 6, 7, 8, 8, 9, 9, 10, 10, 10, 11, 11, 12, 13, 14, 15]
for i in range(20):
    n = random.choice(lengths)
    print(gen_n_words(n))

Когда же принеся в конец файла проекта . И сказал Моисей
Павел сказал Саул еще не получали их в одиночестве
Иависа . Посему так то существует и язык
Авариме на которую пещеру Одоллам и в тот
Разве ты совершила обеты и повел бы менее сей
Но вы совершили они с нею полагая что у
Его и стрелы Свои знамения малую единицу . И скажи
Когда же возврати мне ? Запишется их при нем нечистота
Зачем мятутся язычники и Манассии
Это происходит не принимает Пославшего Меня от зла
Я Господь избавил народ мой . Так приносите сие братиям живущим на овна в usr
И собрались вместе с Иудеями мир . Мы уже сходили они поражены Израильтянами и которые
Иорам и из миров . Придя к преступлениям и они и говорить
На личность ли все ободрились и вы были распростерты расходует
Израилев могут войти . Наклонность
Нему чтобы умножилась неправда .
Иудее пророк Иеремия царю . Если она найдена в груди . И Ты знаешь видишь
Мы создали то попирает его Господь долготерпелив и взойдя на
Тотчас собрались первосвященники и преследо

In [216]:
gen_n_words(10, first_word='UNIX')

'UNIX сфере в которые владели ничем таковым . . Посему'

In [75]:
gen_n_words(12, first_word='алгоритм')

'алгоритм только половина колена дано место для вас в предыдущей даты очень'

Что-то порождать самостоятельно получается, но очень много мусора. Возьмём лучше готовую имплементаию марковской цепи и попытаемся улучшить комедийный эффект.

## План по захвату мира

**Проблема**: не все предложения смешные -- большая часть представляет собой либо что-то библиеподобное, либо программистское.

**Задача**: автоопределять смешные предложения, то есть отлавливать такие предложения, которые, с болбшой вероятностью, содержат слова и из библии, и из программирования.

**Пути решения**:
* через tf-idf
* классификатор, выдающий вероятности!

### Получаем датасет

In [76]:
import numpy as np
import pandas as pd
from nltk.tokenize import sent_tokenize

In [182]:
testament = sent_tokenize(bible + koran)
# testament = sent_tokenize(koran)

In [183]:
print(testament[:15])
len(testament)

['Бытие В начале сотворил Бог небо и землю.', 'Земля же была безвидна и пуста и тьма над бездною и Дух Божий носился над водою.', 'И сказал Бог да будет свет.', 'И стал свет.', 'И увидел Бог свет что он хорош и отделил Бог свет от тьмы.', 'И назвал Бог свет днем а тьму ночью.', 'И был вечер и было утро день один.', 'И сказал Бог да будет твердь посреди воды и да отделяет она воду от воды.', 'И стало так.', 'И создал Бог твердь и отделил воду которая под твердью от воды которая над твердью.', 'И стало так.', 'И назвал Бог твердь небом.', 'И увидел Бог что это хорошо.', 'И был вечер и было утро день второй.', 'И сказал Бог да соберется вода которая под небом в одно место и да явится суша.']


55072

In [184]:
coding = sent_tokenize(unix+unix)
print(coding[:15])
len(coding)

['.', 'Предисловие В последнее время Internet очень часто оказывается в центре внимания и серьезные люди часто болтаются по этому Информационному супершоссе .', 'Компьютерные сети становятся такими же обыденными вещами как телевизоры и микроволновые печи.', 'Inetrnet получает необычно широкое освещение в печати а ученые обсуждают в Usenet возможность проведения исследований Internet культуры.', 'Различные компании работают над новыми методами передачи данных например ATM которые во многих случаях позволяют получить большую скорость передачи чем сейчас.', 'Конечно сети развивались достаточно долгое время.', 'Обычной практикой было создание маленьких локальных сетей в основном распологавшихся в одном здании и соединенных через обычные телефонные линии.', 'Таким образом быстро разраставшийся конгломерат сетей позволял подсоединятся к этой глобальной системе даже маленьким некоммерческим организациям и частным пользователям.', 'Поэтому создание Internet хоста с почтой и новостями предлагаю

29089

In [185]:
sentences = testament + coding
labels = ['testament'] * len(testament) + ['coding'] * len(coding)

In [186]:
df = pd.DataFrame({'sentences' : sentences, 'labels': labels})
df.head()

sentences     labels
0          Бытие В начале сотворил Бог небо и землю.  testament
1  Земля же была безвидна и пуста и тьма над безд...  testament
2                        И сказал Бог да будет свет.  testament
3                                       И стал свет.  testament
4  И увидел Бог свет что он хорош и отделил Бог с...  testament

In [187]:
# перемешаем данные
df = df.sample(frac=1).reset_index(drop=True)
df.head(10)

sentences     labels
0  UUCPNAME разрешает Вам определять различные ho...     coding
1  Что возлюбленному Моему в доме Моем когда в не...  testament
2  У Аллаха величие и у Его посланника и у верующ...  testament
3  Предел Манассии на северной стороне потока и о...  testament
4  Если вы вызываете pall используя следующую ком...     coding
5  Из них буду брать также в священники и левиты ...  testament
6                        Впрочем близок всему конец.  testament
7  И вышел Иона из города и сел с восточной сторо...  testament
8                    О да погибнут адиты народ Худа!  testament
9  Тогда говорит ученикам Своим жатвы много а дел...  testament

In [188]:
# и сохраним, а то сколько можно
df.to_csv('bible_vs_coding.csv', index=False)

In [160]:
!mv bible_vs_coding.csv data/

"mv" ­Ґ пў«пҐвбп ў­гв७­Ґ© Ё«Ё ў­Ґи­Ґ©
Є®¬ ­¤®©, ЁбЇ®«­пҐ¬®© Їа®Ја ¬¬®© Ё«Ё Ї ЄҐв­л¬ д ©«®¬.


In [189]:
from sklearn.model_selection import train_test_split

In [190]:
X_train, X_test, y_train, y_test = train_test_split(df['sentences'], df['labels'], test_size=0.2, random_state=42)

### Предобработка

In [191]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
stopset = stopwords.words('russian')
stopset[:10]

['и', 'в', 'во', 'не', 'что', 'он', 'на', 'я', 'с', 'со']

In [192]:
from string import punctuation
punct = list(punctuation)
punct[:15]

['!', '"', '#', '$', '%', '&', "'", '(', ')', '*', '+', ',', '-', '.', '/']

In [258]:
from pymystem3 import Mystem
def preproc_lemmitize(text):
#     m = Mystem()
#     text = m.lemmatize(text.lower()) # приводим к нижнему регистру и токенизируем
    return [w for w in text if w not in stopset + punct]

In [200]:
preproc_lemmitize('И сказал Бог: да будет свет.')

[' ', 'сказать', ' ', 'бог', ': ', ' ', ' ', 'свет', '\n']

### Классификация

In [229]:
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.naive_bayes import MultinomialNB

Перед наивным Байесом я попробовала DecisionTreeClassifier. Он работал с f-мерой ~96, но очень плохо выдавал условные вероятности (в основном 0.0, 1.0). У MultinomialNB и лучше f-мера, и условные вероятности позволяют принимать решение о "нетипичности" фразы.

Препроцессинг с помощью mystem работал слишком долго.

In [240]:
# dt = Pipeline(
#     [('vect', TfidfVectorizer(min_df=10)),
#     ('tree', DecisionTreeClassifier(random_state=42))]
# )

dt = Pipeline(
    [('vect', TfidfVectorizer(min_df=10)),
    ('tree', RandomForestClassifier())]
)

dt.fit(X_train, y=y_train)

Pipeline(steps=[('vect', TfidfVectorizer(min_df=10)),
                ('tree', RandomForestClassifier())])

In [241]:
print(classification_report(y_test, dt.predict(X_test)))
print(accuracy_score(y_test, dt.predict(X_test)))

              precision    recall  f1-score   support

      coding       0.99      0.88      0.93      5831
   testament       0.94      0.99      0.97     11002

    accuracy                           0.95     16833
   macro avg       0.96      0.94      0.95     16833
weighted avg       0.96      0.95      0.95     16833

0.9547317768668686


In [249]:
# ppl = Pipeline(
#     [('vect', TfidfVectorizer(min_df=5, tokenizer=my_preprocessor)),
#     ('nb', MultinomialNB())]
# )
ppl = Pipeline(
    [('vect', TfidfVectorizer(min_df=5, tokenizer=my_preprocessor)),
    ('nb', RandomForestClassifier())]
)
ppl.fit(X_train, y=y_train)

Pipeline(steps=[('vect',
                 TfidfVectorizer(min_df=5,
                                 tokenizer=<function my_preprocessor at 0x0000015EC43445E0>)),
                ('nb', RandomForestClassifier())])

In [250]:
print(classification_report(y_test, ppl.predict(X_test)))
print(accuracy_score(y_test, ppl.predict(X_test)))

              precision    recall  f1-score   support

      coding       0.98      0.89      0.93      5831
   testament       0.94      0.99      0.97     11002

    accuracy                           0.95     16833
   macro avg       0.96      0.94      0.95     16833
weighted avg       0.96      0.95      0.95     16833

0.9548505911008138


In [251]:
ppl.predict_proba(['Но ведь тоrда тщательно выверенная процедура PARTIТION не будет живущих, ибо'])

array([[0.04, 0.96]])

Урааа, работает! Теперь можно захватывать мир.

In [244]:
print(ppl.predict_proba(['Шаг 2 выполняется ровно n раз, потому что ячмень выколосился, а лен осеменился; а пшеница и полба не побиты, потому что Господь зовет отрока.']))
print(ppl.predict_proba(['Потом пошел Авимелех на гору Селмон, сам и дом царский для себя.']))
print(ppl.predict_proba(['Процедура Bu1LD-HUFFМAN-TREE служит примером жадного алгоритма, в котором длина строк превышает 4 байта?']))

[[0.44999185 0.55000815]]
[[8.34707322e-04 9.99165293e-01]]
[[0.94402701 0.05597299]]


In [245]:
# и модель сохраним, давно пора

import pickle

with open('algtest_classifyer.clf', 'wb') as f:
    pickle.dump(ppl, f)

In [176]:
!ls -lh *.clf

"ls" ­Ґ пў«пҐвбп ў­гв७­Ґ© Ё«Ё ў­Ґи­Ґ©
Є®¬ ­¤®©, ЁбЇ®«­пҐ¬®© Їа®Ја ¬¬®© Ё«Ё Ї ЄҐв­л¬ д ©«®¬.


### Захват мира

Напишем функцию, которая находит что-то весёлое:

In [209]:
def isFunny(sent, model, min_p, max_p):
    return min_p < model.predict_proba([sent])[0][1] < max_p

**Настройки функции**: с min_p и max_p можно играться. Наибольшая точность достигается в районе 0.01 и 0.97 соответственно. Однако, так как нас не так сильно беспокоят false negative -- главное, чтобы не было false positive -- лучше сделать этот порог повыше.

In [265]:
for i in range(100):
#     sent = text_m.make_sentence()
    sent = gen_n_words(random.randint(5,12), first_word='Аллах')
    if isFunny(sent, ppl, 0.01, 0.97) == True:
        print(re.sub(r'[^\w\s]','', sent))
        print('')

Аллах захотел ходить по букве ему также

Аллах не являются so NORM e E X сеанс работы чтобы он

Аллах сделает то они скажут им для систем 

Аллах наблюдатель  Он вызывает команду которая была на носителе

Аллах говорит Господь море и надежный доступ пользователей могут они неусыпно пекутся

Аллах знает то что будет прибавить линии только

Аллах держит информацию  Ибо

Аллах отрекается от лукавства  Для систем

Аллах не клевещите и полей с нами   У

Аллах приведет муж поспешил выдать arp v   Но рушится

Аллах знает NYS использовал именованный сервер через

Аллах подчинил солнце и жена неверующая освящается словом истины которая есть

Аллах  а если следующая строка и располагал воду покупайте у детей

Аллах тех кому оказалось их использовать

Аллах пожелал сами назвали эти имена файлов

Аллах устроил   и сказал мне с места поиск в Приложении

Аллах благодарен  incoming  Вот что smail  Вы

Аллах слышащий ведающий скрытое в задние части ядра который наречен

